# Generated by Django 4.1.1 on 2022-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_64_room_capchatiktok'),
    ]

    operations = [
        migrations.AddField(
            model_name='capchatiktok',
            name='codeImg_big',
            field=models.TextField(default='null', max_length=300000),
        ),
        migrations.AddField(
            model_name='capchatiktok',
            name='codeImg_small',
            field=models.TextField(default='null', max_length=300000),
        ),
        migrations.AddField(
            model_name='capchatiktok',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
