# Generated by Django 4.1.1 on 2022-10-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_capchatiktok_codeimg_big_capchatiktok_codeimg_small_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capchatiktok',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='capchatiktok',
            name='image_small',
        ),
    ]
