# Generated by Django 4.1.1 on 2022-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_capchatiktok_image_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capchatiktok',
            name='codeImg_pre',
            field=models.TextField(default='null', max_length=300000),
        ),
    ]
